name: Merge Sync Branch to Main

on:
  push:
    branches:
      - sync-branch

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Merge sync-branch into main
        run: |
          git merge sync-branch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
