name: Sync with Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v3
        with:
          ref: main  # Check out the main branch of your fork
          token: ${{ secrets.PAT }}  # Use your PAT instead of GITHUB_TOKEN
          clean: true  # Ensure it's a fresh clone

      - name: Set GitHub committer identity
        run: |
          git config --global user.email "mourabitiziyad@gmail.com"
          git config --global user.name "Ziyad Mourabiti"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/DigitalProductInnovationAndDevelopment/Security-Compliance-Assessment.git

      - name: Fetch upstream repository
        run: git fetch upstream

      - name: Create or checkout the sync branch
        run: |
          git checkout -b sync-branch || git checkout sync-branch

      - name: Merge upstream changes into sync-branch, accepting theirs on conflicts
        run: git merge upstream/main --no-ff --allow-unrelated-histories -X theirs

      - name: Filter out unwanted workflow files (skip the sync.yml)
        run: |
          find .github/workflows/ -type f ! -name 'sync.yml' -exec git rm --cached --ignore-unmatch {} +
          git commit -m "Remove unwanted workflows" || echo "No changes to commit"

      - name: Push changes to sync-branch
        run: |
          git push origin sync-branch --force --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Use the PAT instead of the default GITHUB_TOKEN
